/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PathogensIndexImport } from './routes/pathogens/index'
import { Route as PathogensPathogenIdImport } from './routes/pathogens/$pathogenId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PathogensIndexRoute = PathogensIndexImport.update({
  id: '/pathogens/',
  path: '/pathogens/',
  getParentRoute: () => rootRoute,
} as any)

const PathogensPathogenIdRoute = PathogensPathogenIdImport.update({
  id: '/pathogens/$pathogenId',
  path: '/pathogens/$pathogenId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pathogens/$pathogenId': {
      id: '/pathogens/$pathogenId'
      path: '/pathogens/$pathogenId'
      fullPath: '/pathogens/$pathogenId'
      preLoaderRoute: typeof PathogensPathogenIdImport
      parentRoute: typeof rootRoute
    }
    '/pathogens/': {
      id: '/pathogens/'
      path: '/pathogens'
      fullPath: '/pathogens'
      preLoaderRoute: typeof PathogensIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pathogens/$pathogenId': typeof PathogensPathogenIdRoute
  '/pathogens': typeof PathogensIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pathogens/$pathogenId': typeof PathogensPathogenIdRoute
  '/pathogens': typeof PathogensIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pathogens/$pathogenId': typeof PathogensPathogenIdRoute
  '/pathogens/': typeof PathogensIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pathogens/$pathogenId' | '/pathogens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pathogens/$pathogenId' | '/pathogens'
  id: '__root__' | '/' | '/pathogens/$pathogenId' | '/pathogens/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathogensPathogenIdRoute: typeof PathogensPathogenIdRoute
  PathogensIndexRoute: typeof PathogensIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathogensPathogenIdRoute: PathogensPathogenIdRoute,
  PathogensIndexRoute: PathogensIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pathogens/$pathogenId",
        "/pathogens/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pathogens/$pathogenId": {
      "filePath": "pathogens/$pathogenId.tsx"
    },
    "/pathogens/": {
      "filePath": "pathogens/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
